#!/usr/bin/env bash
set -euo pipefail

# End-to-end test: lift RISC-V code to LLVM IR, compile to host native, and run.
#
# Usage: test_riscv_lift_and_run.sh <remill-lift> <clang>

if [[ $# -lt 2 ]]; then
  echo "Usage: $0 <remill-lift-binary> <clang-binary>"
  exit 1
fi

REMILL_LIFT="$1"
CLANG="$2"

TMPDIR="$(mktemp -d)"
trap 'rm -rf "$TMPDIR"' EXIT

# RISC-V 64-bit instructions encoding a trivial "add 42" function:
#   0x1000: addi a0, a0, 42   (0x02A50513)
#   0x1004: ret                (0x00008067)
#
# In little-endian hex bytes:
BYTES="1305a50267800000"

echo "=== Step 1: Lift RISC-V bytes to LLVM IR ==="
"$REMILL_LIFT" \
  --arch riscv64 \
  --os linux \
  --address 0x1000 \
  --bytes "$BYTES" \
  --ir_out "$TMPDIR/lifted.ll" \
  --signature "X10(X10)" \
  --mute_state_escape

echo "Lifted IR written to $TMPDIR/lifted.ll"

echo "=== Step 2: Create native harness ==="
cat > "$TMPDIR/harness.c" << 'HARNESS_EOF'
#include <inttypes.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>

/* Stubs for remill intrinsics that may survive optimization. */
void *__remill_function_return(void *s, uint64_t pc, void *m) {
  return m;
}
void *__remill_missing_block(void *s, uint64_t pc, void *m) {
  return m;
}
void *__remill_error(void *s, uint64_t pc, void *m) {
  return m;
}
void *__remill_function_call(void *s, uint64_t pc, void *m) {
  return m;
}
void *__remill_jump(void *s, uint64_t pc, void *m) {
  return m;
}
uint64_t __remill_symbolic_STACK(void) {
  return 0x7fff0000;
}

/* Wrapper generated by remill-lift --signature "X10(X10)" */
extern uint64_t call_sub_1000(uint64_t);

int main(void) {
  /* 100 + 42 == 142 */
  uint64_t result = call_sub_1000(100);
  if (result == 142) {
    printf("PASS: call_sub_1000(100) == %" PRIu64 "\n", result);
    return EXIT_SUCCESS;
  }
  fprintf(stderr, "FAIL: expected 142, got %" PRIu64 "\n", result);
  return EXIT_FAILURE;
}
HARNESS_EOF

echo "=== Step 3: Compile lifted IR + harness to host native ==="
# Compile LLVM IR to native object (clang handles the target override)
"$CLANG" -Wno-override-module -O2 -c \
  "$TMPDIR/lifted.ll" -o "$TMPDIR/lifted.o"
# Compile harness (force C mode since $CLANG may be clang++) and link
"$CLANG" -x c -O2 -c "$TMPDIR/harness.c" -o "$TMPDIR/harness.o"
"$CLANG" -O2 "$TMPDIR/harness.o" "$TMPDIR/lifted.o" -o "$TMPDIR/test_binary"

echo "=== Step 4: Run the native binary ==="
"$TMPDIR/test_binary"
