FUNCTION(SET_LIBRARY_TARGET NAMESPACE LIB_NAME DEBUG_LIB_FILE_NAME RELEASE_LIB_FILE_NAME INCLUDE_DIR)
    ADD_LIBRARY(${NAMESPACE}::${LIB_NAME} STATIC IMPORTED)
    SET_TARGET_PROPERTIES(${NAMESPACE}::${LIB_NAME} PROPERTIES
                          IMPORTED_CONFIGURATIONS "RELEASE;DEBUG"
                          IMPORTED_LOCATION_RELEASE "${RELEASE_LIB_FILE_NAME}"
                          IMPORTED_LOCATION_DEBUG "${DEBUG_LIB_FILE_NAME}"
                          INTERFACE_INCLUDE_DIRECTORIES "${INCLUDE_DIR}"
                          )
    SET(${NAMESPACE}_${LIB_NAME}_FOUND 1)
ENDFUNCTION()

GET_FILENAME_COMPONENT(ROOT "${CMAKE_CURRENT_LIST_FILE}" PATH)
GET_FILENAME_COMPONENT(ROOT "${ROOT}" PATH)
GET_FILENAME_COMPONENT(ROOT "${ROOT}" PATH)

# TODO Debug libs
# "${ROOT}/debug/lib/xed"
SET_LIBRARY_TARGET("XED" "XED" "${ROOT}/lib/libxed${CMAKE_STATIC_LIBRARY_SUFFIX}" "${ROOT}/lib/libxed${CMAKE_STATIC_LIBRARY_SUFFIX}" "${ROOT}/include/xed")
SET_LIBRARY_TARGET("ILD" "XED" "${ROOT}/lib/libxed-ild${CMAKE_STATIC_LIBRARY_SUFFIX}" "${ROOT}/lib/libxed-ild${CMAKE_STATIC_LIBRARY_SUFFIX}" "${ROOT}/include/xed")
#
#
#
#set(XED_LIBRARY_DIR "${CMAKE_CURRENT_LIST_DIR}/../../../lib")
#set(XED_LIBRARIES "${XED_LIBRARY_DIR}/xed${CMAKE_STATIC_LIBRARY_SUFFIX}" "${XED_LIBRARY_DIR}/xed-ild${CMAKE_STATIC_LIBRARY_SUFFIX}")
#set(XED_INCLUDE_DIRS "${CMAKE_CURRENT_LIST_DIR}/../../../include")
#
## https://stackoverflow.com/a/48397346
#add_library(XED::Main STATIC IMPORTED)
#set_target_properties(XED::Main PROPERTIES
#    IMPORTED_LOCATION "${XED_LIBRARY_DIR}/xed${CMAKE_STATIC_LIBRARY_SUFFIX}"
#)
#
#add_library(XED::ILD STATIC IMPORTED)
#set_target_properties(XED::ILD PROPERTIES
#    IMPORTED_LOCATION "${XED_LIBRARY_DIR}/xed-ild${CMAKE_STATIC_LIBRARY_SUFFIX}"
#)
#
#add_library(XED::XED INTERFACE IMPORTED)
#set_target_properties(XED::XED PROPERTIES
#    INTERFACE_INCLUDE_DIRECTORIES "${XED_INCLUDE_DIRS}"
#    INTERFACE_LINK_LIBRARIES "XED::Main;XED::ILD"
#)
