/* Copyright 2016 Peter Goodman (peter@trailofbits.com), all rights reserved. */

#ifndef REMILL_ARCH_X86_SEMANTICS_NOP_H_
#define REMILL_ARCH_X86_SEMANTICS_NOP_H_

namespace {

template <typename...Types>
DEF_SEM(NOP_IMPL, Types...) {
  return memory;
}

}  // namespace

DEF_ISEL_Rn(NOP_GPRv_0F18r0, NOP_IMPL);
DEF_ISEL_Rn(NOP_GPRv_0F18r1, NOP_IMPL);
DEF_ISEL_Rn(NOP_GPRv_0F18r2, NOP_IMPL);
DEF_ISEL_Rn(NOP_GPRv_0F18r3, NOP_IMPL);
DEF_ISEL_Rn(NOP_GPRv_0F18r4, NOP_IMPL);
DEF_ISEL_Rn(NOP_GPRv_0F18r5, NOP_IMPL);
DEF_ISEL_Rn(NOP_GPRv_0F18r6, NOP_IMPL);
DEF_ISEL_Rn(NOP_GPRv_0F18r7, NOP_IMPL);

DEF_ISEL_Rn_Rn(NOP_GPRv_GPRv_0F19, NOP_IMPL);
DEF_ISEL_Rn_Rn(NOP_GPRv_GPRv_0F1C, NOP_IMPL);
DEF_ISEL_Rn_Rn(NOP_GPRv_GPRv_0F1D, NOP_IMPL);
DEF_ISEL_Rn_Rn(NOP_GPRv_GPRv_0F1E, NOP_IMPL);
DEF_ISEL_Rn_Rn(NOP_GPRv_GPRv_0F1F, NOP_IMPL);

DEF_ISEL_Mn(NOP_MEMv_0F18r4, NOP_IMPL);
DEF_ISEL_Mn(NOP_MEMv_0F18r5, NOP_IMPL);
DEF_ISEL_Mn(NOP_MEMv_0F18r6, NOP_IMPL);
DEF_ISEL_Mn(NOP_MEMv_0F18r7, NOP_IMPL);

DEF_ISEL_Mn_Rn(NOP_MEMv_GPRv_0F19, NOP_IMPL);
DEF_ISEL_Mn_Rn(NOP_MEMv_GPRv_0F1C, NOP_IMPL);
DEF_ISEL_Mn_Rn(NOP_MEMv_GPRv_0F1D, NOP_IMPL);
DEF_ISEL_Mn_Rn(NOP_MEMv_GPRv_0F1E, NOP_IMPL);
DEF_ISEL_Mn_Rn(NOP_MEMv_GPRv_0F1F, NOP_IMPL);

DEF_ISEL(NOP_90) = NOP_IMPL<>;

DEF_ISEL_Rn_Rn(NOP_GPRv_GPRv_0F0D, NOP_IMPL);
DEF_ISEL_Rn_Rn(NOP_GPRv_GPRv_0F1A, NOP_IMPL);
DEF_ISEL_Rn_Rn(NOP_GPRv_GPRv_0F1B, NOP_IMPL);

DEF_ISEL_Rn_Mn(NOP_GPRv_MEMv_0F1A, NOP_IMPL);
DEF_ISEL_Rn_Mn(NOP_GPRv_MEM_0F1B, NOP_IMPL);

/*

401 FENI8087_NOP FENI8087_NOP X87_ALU X87 X87 ATTRIBUTES: NOP NOTSX
546 FSETPM287_NOP FSETPM287_NOP X87_ALU X87 X87 ATTRIBUTES: NOP NOTSX
1286 FDISI8087_NOP FDISI8087_NOP X87_ALU X87 X87 ATTRIBUTES: NOP NOTSX
 */

#endif  // REMILL_ARCH_X86_SEMANTICS_NOP_H_
