/* Copyright 2016 Peter Goodman (peter@trailofbits.com), all rights reserved. */

DEF_ISEL_SEM(CLWB_MEMmprefetch) {}
DEF_ISEL_SEM(PREFETCH_RESERVED_0F0Dr4, M8) {}
DEF_ISEL_SEM(PREFETCH_RESERVED_0F0Dr5, M8) {}
DEF_ISEL_SEM(PREFETCH_RESERVED_0F0Dr6, M8) {}
DEF_ISEL_SEM(PREFETCH_RESERVED_0F0Dr7, M8) {}
DEF_ISEL_SEM(PREFETCHT2_MEMmprefetch, M8) {}
DEF_ISEL_SEM(PREFETCHT1_MEMmprefetch, M8) {}
DEF_ISEL_SEM(PREFETCHT0_MEMmprefetch, M8) {}
DEF_ISEL_SEM(CLFLUSHOPT_MEMmprefetch, M8) {}
DEF_ISEL_SEM(PREFETCH_EXCLUSIVE_MEMmprefetch, M8) {}
IF_AVX512(DEF_ISEL_SEM(PREFETCHWT1_MEMu8, M8) {})
DEF_ISEL_SEM(PREFETCHW_0F0Dr1, M8) {}
DEF_ISEL_SEM(PREFETCHW_0F0Dr3, M8) {}
DEF_ISEL_SEM(PREFETCHNTA_MEMmprefetch, M8) {}
