/* Copyright 2016 Peter Goodman (peter@trailofbits.com), all rights reserved. */

namespace {
DEF_SEM(PREFETCH, M8) {}

}  // namespace

DEF_ISEL(CLWB_MEMmprefetch) = DoNothing;
DEF_ISEL(PREFETCH_RESERVED_0F0Dr4) = PREFETCH;
DEF_ISEL(PREFETCH_RESERVED_0F0Dr5) = PREFETCH;
DEF_ISEL(PREFETCH_RESERVED_0F0Dr6) = PREFETCH;
DEF_ISEL(PREFETCH_RESERVED_0F0Dr7) = PREFETCH;
DEF_ISEL(PREFETCHT2_MEMmprefetch) = PREFETCH;
DEF_ISEL(PREFETCHT1_MEMmprefetch) = PREFETCH;
DEF_ISEL(PREFETCHT0_MEMmprefetch) = PREFETCH;
DEF_ISEL(CLFLUSHOPT_MEMmprefetch) = PREFETCH;
DEF_ISEL(PREFETCH_EXCLUSIVE_MEMmprefetch) = PREFETCH;
IF_AVX512(DEF_ISEL(PREFETCHWT1_MEMu8) = PREFETCH;)
DEF_ISEL(PREFETCHW_0F0Dr1) = PREFETCH;
DEF_ISEL(PREFETCHW_0F0Dr3) = PREFETCH;
DEF_ISEL(PREFETCHNTA_MEMmprefetch) = PREFETCH;
