/* Copyright 2015 Peter Goodman (peter@trailofbits.com), all rights reserved. */

namespace {

template <typename D, typename S>
DEF_SEM(MOV, D dst, S src) {
  W(dst) = R(src);
}

}  // namespace

DEF_ISEL(MOV_GPR8_IMMb_C6r0_8) = MOV<R8W, I8>;
DEF_ISEL(MOV_MEMb_IMMb_8) = MOV<M8W, I8>;
DEF_ISEL_RnW_In(MOV_GPRv_IMMz, MOV);
DEF_ISEL_MnW_In(MOV_MEMv_IMMz, MOV);
DEF_ISEL(MOV_GPR8_GPR8_88_8) = MOV<R8W, R8>;
DEF_ISEL(MOV_MEMb_GPR8_8) = MOV<M8W, R8>;
DEF_ISEL_MnW_Rn(MOV_MEMv_GPRv, MOV);
DEF_ISEL_RnW_Rn(MOV_GPRv_GPRv_89, MOV);
DEF_ISEL(MOV_GPR8_MEMb_8) = MOV<R8W, M8>;
DEF_ISEL(MOV_GPR8_GPR8_8A_8) = MOV<R8W, R8>;
DEF_ISEL_RnW_Mn(MOV_GPRv_MEMv, MOV);
DEF_ISEL_MnW_Rn(MOV_MEMv_GPRv_8B, MOV);
DEF_ISEL(MOV_AL_MEMb_8) = MOV<R8W, M8>;
DEF_ISEL_RnW_Mn(MOV_OrAX_MEMv, MOV);
DEF_ISEL(MOV_MEMb_AL_8) = MOV<M8W, R8>;
DEF_ISEL_MnW_Rn(MOV_MEMv_OrAX, MOV);
DEF_ISEL(MOV_GPR8_IMMb_D0_8) = MOV<R8W, I8>;
DEF_ISEL_RnW_In(MOV_GPRv_IMMv, MOV);

/*

1148 MOV MOV_MEMw_SEG DATAXFER BASE I86 ATTRIBUTES:
1149 MOV MOV_GPRv_SEG DATAXFER BASE I86 ATTRIBUTES: SCALABLE
1150 MOV MOV_SEG_MEMw DATAXFER BASE I86 ATTRIBUTES: NOTSX
1151 MOV MOV_SEG_GPR16 DATAXFER BASE I86 ATTRIBUTES: NOTSX

1205 MOVDDUP MOVDDUP_XMMdq_MEMq DATAXFER SSE3 SSE3 ATTRIBUTES: UNALIGNED
1206 MOVDDUP MOVDDUP_XMMdq_XMMq DATAXFER SSE3 SSE3 ATTRIBUTES: UNALIGNED

1253 MOVNTSS MOVNTSS_MEMd_XMMd DATAXFER SSE4A SSE4A ATTRIBUTES:

1288 MOVNTSD MOVNTSD_MEMq_XMMq DATAXFER SSE4A SSE4A ATTRIBUTES:

1354 MOVAPS MOVAPS_XMMps_MEMps DATAXFER SSE SSE ATTRIBUTES: REQUIRES_ALIGNMENT SIMD_PACKED_ALIGNMENT
1355 MOVAPS MOVAPS_XMMps_XMMps_0F28 DATAXFER SSE SSE ATTRIBUTES: REQUIRES_ALIGNMENT SIMD_PACKED_ALIGNMENT
1356 MOVAPS MOVAPS_MEMps_XMMps DATAXFER SSE SSE ATTRIBUTES: REQUIRES_ALIGNMENT SIMD_PACKED_ALIGNMENT
1357 MOVAPS MOVAPS_XMMps_XMMps_0F29 DATAXFER SSE SSE ATTRIBUTES: REQUIRES_ALIGNMENT SIMD_PACKED_ALIGNMENT

1360 MOVD MOVD_XMMdq_MEMd DATAXFER SSE2 SSE2 ATTRIBUTES: UNALIGNED
1361 MOVD MOVD_XMMdq_GPR32 DATAXFER SSE2 SSE2 ATTRIBUTES: UNALIGNED
1362 MOVD MOVD_XMMdq_MEMd DATAXFER SSE2 SSE2 ATTRIBUTES: UNALIGNED
1363 MOVD MOVD_XMMdq_GPR32 DATAXFER SSE2 SSE2 ATTRIBUTES: UNALIGNED
1364 MOVD MOVD_MEMd_XMMd DATAXFER SSE2 SSE2 ATTRIBUTES: UNALIGNED
1365 MOVD MOVD_GPR32_XMMd DATAXFER SSE2 SSE2 ATTRIBUTES: UNALIGNED
1366 MOVD MOVD_MEMd_XMMd DATAXFER SSE2 SSE2 ATTRIBUTES: UNALIGNED
1367 MOVD MOVD_GPR32_XMMd DATAXFER SSE2 SSE2 ATTRIBUTES: UNALIGNED
1368 MOVD MOVD_MMXq_MEMd DATAXFER MMX PENTIUMMMX ATTRIBUTES: NOTSX UNALIGNED
1369 MOVD MOVD_MMXq_GPR32 DATAXFER MMX PENTIUMMMX ATTRIBUTES: NOTSX UNALIGNED
1370 MOVD MOVD_MMXq_MEMd DATAXFER MMX PENTIUMMMX ATTRIBUTES: NOTSX UNALIGNED
1371 MOVD MOVD_MMXq_GPR32 DATAXFER MMX PENTIUMMMX ATTRIBUTES: NOTSX UNALIGNED
1372 MOVD MOVD_MEMd_MMXd DATAXFER MMX PENTIUMMMX ATTRIBUTES: NOTSX UNALIGNED
1373 MOVD MOVD_GPR32_MMXd DATAXFER MMX PENTIUMMMX ATTRIBUTES: NOTSX UNALIGNED
1374 MOVD MOVD_MEMd_MMXd DATAXFER MMX PENTIUMMMX ATTRIBUTES: NOTSX UNALIGNED
1375 MOVD MOVD_GPR32_MMXd DATAXFER MMX PENTIUMMMX ATTRIBUTES: NOTSX UNALIGNED

1384 MOVAPD MOVAPD_XMMpd_MEMpd DATAXFER SSE2 SSE2 ATTRIBUTES: REQUIRES_ALIGNMENT SIMD_PACKED_ALIGNMENT
1385 MOVAPD MOVAPD_XMMpd_XMMpd_0F28 DATAXFER SSE2 SSE2 ATTRIBUTES: REQUIRES_ALIGNMENT SIMD_PACKED_ALIGNMENT
1386 MOVAPD MOVAPD_MEMpd_XMMpd DATAXFER SSE2 SSE2 ATTRIBUTES: REQUIRES_ALIGNMENT SIMD_PACKED_ALIGNMENT
1387 MOVAPD MOVAPD_XMMpd_XMMpd_0F29 DATAXFER SSE2 SSE2 ATTRIBUTES: REQUIRES_ALIGNMENT SIMD_PACKED_ALIGNMENT

1405 MOVDQ2Q MOVDQ2Q_MMXq_XMMq DATAXFER SSE2 SSE2 ATTRIBUTES: MMX_EXCEPT NOTSX

1416 MOVMSKPD MOVMSKPD_GPR32_XMMpd DATAXFER SSE2 SSE2 ATTRIBUTES:

1437 MOVHPD MOVHPD_XMMsd_MEMq DATAXFER SSE2 SSE2 ATTRIBUTES: UNALIGNED
1438 MOVHPD MOVHPD_MEMq_XMMsd DATAXFER SSE2 SSE2 ATTRIBUTES: UNALIGNED

1449 MOVHPS MOVHPS_XMMq_MEMq DATAXFER SSE SSE ATTRIBUTES: UNALIGNED
1450 MOVHPS MOVHPS_MEMq_XMMps DATAXFER SSE SSE ATTRIBUTES: UNALIGNED

1461 MOVUPD MOVUPD_XMMpd_MEMpd DATAXFER SSE2 SSE2 ATTRIBUTES: UNALIGNED
1462 MOVUPD MOVUPD_XMMpd_XMMpd_0F10 DATAXFER SSE2 SSE2 ATTRIBUTES: UNALIGNED
1463 MOVUPD MOVUPD_MEMpd_XMMpd DATAXFER SSE2 SSE2 ATTRIBUTES: UNALIGNED
1464 MOVUPD MOVUPD_XMMpd_XMMpd_0F11 DATAXFER SSE2 SSE2 ATTRIBUTES: UNALIGNED

1470 MOVZX MOVZX_GPRv_MEMb DATAXFER BASE I386 ATTRIBUTES: SCALABLE
1471 MOVZX MOVZX_GPRv_GPR8 DATAXFER BASE I386 ATTRIBUTES: SCALABLE
1472 MOVZX MOVZX_GPRv_MEMw DATAXFER BASE I386 ATTRIBUTES: SCALABLE
1473 MOVZX MOVZX_GPRv_GPR16 DATAXFER BASE I386 ATTRIBUTES: SCALABLE

1476 MOVUPS MOVUPS_XMMps_MEMps DATAXFER SSE SSE ATTRIBUTES: UNALIGNED
1477 MOVUPS MOVUPS_XMMps_XMMps_0F10 DATAXFER SSE SSE ATTRIBUTES: UNALIGNED
1478 MOVUPS MOVUPS_MEMps_XMMps DATAXFER SSE SSE ATTRIBUTES: UNALIGNED
1479 MOVUPS MOVUPS_XMMps_XMMps_0F11 DATAXFER SSE SSE ATTRIBUTES: UNALIGNED

1657 MOVDQA MOVDQA_MEMdq_XMMdq DATAXFER SSE2 SSE2 ATTRIBUTES: REQUIRES_ALIGNMENT SIMD_PACKED_ALIGNMENT
1658 MOVDQA MOVDQA_XMMdq_XMMdq_0F7F DATAXFER SSE2 SSE2 ATTRIBUTES: REQUIRES_ALIGNMENT SIMD_PACKED_ALIGNMENT
1659 MOVDQA MOVDQA_XMMdq_MEMdq DATAXFER SSE2 SSE2 ATTRIBUTES: REQUIRES_ALIGNMENT SIMD_PACKED_ALIGNMENT
1660 MOVDQA MOVDQA_XMMdq_XMMdq_0F6F DATAXFER SSE2 SSE2 ATTRIBUTES: REQUIRES_ALIGNMENT SIMD_PACKED_ALIGNMENT

1679 MOVNTPD MOVNTPD_MEMdq_XMMpd DATAXFER SSE2 SSE2 ATTRIBUTES: NOTSX REQUIRES_ALIGNMENT

1725 MOVNTPS MOVNTPS_MEMdq_XMMps DATAXFER SSE SSE ATTRIBUTES: NOTSX REQUIRES_ALIGNMENT

1735 MASKMOVQ MASKMOVQ_MMXq_MMXq DATAXFER MMX PENTIUMMMX ATTRIBUTES: FIXED_BASE0 MASKOP NOTSX

1744 MOVHLPS MOVHLPS_XMMq_XMMq DATAXFER SSE SSE ATTRIBUTES:

1785 BSWAP BSWAP_GPRv DATAXFER BASE I486REAL ATTRIBUTES: SCALABLE

2001 VMOVMSKPD VMOVMSKPD_GPR32d_XMMdq DATAXFER AVX AVX ATTRIBUTES:
2002 VMOVMSKPD VMOVMSKPD_GPR32d_YMMqq DATAXFER AVX AVX ATTRIBUTES:

2003 VMOVSD VMOVSD_XMMdq_MEMq DATAXFER AVX AVX ATTRIBUTES: SIMD_SCALAR
2004 VMOVSD VMOVSD_XMMdq_XMMdq_XMMq_10 DATAXFER AVX AVX ATTRIBUTES: SIMD_SCALAR
2005 VMOVSD VMOVSD_MEMq_XMMq DATAXFER AVX AVX ATTRIBUTES: SIMD_SCALAR
2006 VMOVSD VMOVSD_XMMdq_XMMdq_XMMq_11 DATAXFER AVX AVX ATTRIBUTES: SIMD_SCALAR

2007 VMOVMSKPS VMOVMSKPS_GPR32d_XMMdq DATAXFER AVX AVX ATTRIBUTES:
2008 VMOVMSKPS VMOVMSKPS_GPR32d_YMMqq DATAXFER AVX AVX ATTRIBUTES:

2013 VMOVSS VMOVSS_XMMdq_MEMd DATAXFER AVX AVX ATTRIBUTES: SIMD_SCALAR
2014 VMOVSS VMOVSS_XMMdq_XMMdq_XMMd_10 DATAXFER AVX AVX ATTRIBUTES: SIMD_SCALAR
2015 VMOVSS VMOVSS_MEMd_XMMd DATAXFER AVX AVX ATTRIBUTES: SIMD_SCALAR
2016 VMOVSS VMOVSS_XMMdq_XMMdq_XMMd_11 DATAXFER AVX AVX ATTRIBUTES: SIMD_SCALAR

2033 VMOVQ VMOVQ_XMMdq_MEMq_6E DATAXFER AVX AVX ATTRIBUTES:
2034 VMOVQ VMOVQ_XMMdq_GPR64q DATAXFER AVX AVX ATTRIBUTES:
2035 VMOVQ VMOVQ_MEMq_XMMq_7E DATAXFER AVX AVX ATTRIBUTES:
2036 VMOVQ VMOVQ_GPR64q_XMMq DATAXFER AVX AVX ATTRIBUTES:
2037 VMOVQ VMOVQ_XMMdq_MEMq_7E DATAXFER AVX AVX ATTRIBUTES:
2038 VMOVQ VMOVQ_XMMdq_XMMq_7E DATAXFER AVX AVX ATTRIBUTES:
2039 VMOVQ VMOVQ_MEMq_XMMq_D6 DATAXFER AVX AVX ATTRIBUTES:
2040 VMOVQ VMOVQ_XMMdq_XMMq_D6 DATAXFER AVX AVX ATTRIBUTES:
2041 VMOVD VMOVD_XMMdq_MEMd DATAXFER AVX AVX ATTRIBUTES:
2042 VMOVD VMOVD_XMMdq_GPR32d DATAXFER AVX AVX ATTRIBUTES:
2043 VMOVD VMOVD_MEMd_XMMd DATAXFER AVX AVX ATTRIBUTES:
2044 VMOVD VMOVD_GPR32d_XMMd DATAXFER AVX AVX ATTRIBUTES:

2165 VMOVDDUP VMOVDDUP_XMMdq_MEMq DATAXFER AVX AVX ATTRIBUTES:
2166 VMOVDDUP VMOVDDUP_XMMdq_XMMdq DATAXFER AVX AVX ATTRIBUTES:
2167 VMOVDDUP VMOVDDUP_YMMqq_MEMqq DATAXFER AVX AVX ATTRIBUTES:
2168 VMOVDDUP VMOVDDUP_YMMqq_YMMqq DATAXFER AVX AVX ATTRIBUTES:

2196 VMOVNTDQA VMOVNTDQA_YMMqq_MEMqq DATAXFER AVX2 AVX2 ATTRIBUTES: AVX_REQUIRES_ALIGNMENT NOTSX

2334 VMOVDQA VMOVDQA_XMMdq_MEMdq DATAXFER AVX AVX ATTRIBUTES: AVX_REQUIRES_ALIGNMENT REQUIRES_ALIGNMENT
2335 VMOVDQA VMOVDQA_XMMdq_XMMdq_6F DATAXFER AVX AVX ATTRIBUTES: AVX_REQUIRES_ALIGNMENT REQUIRES_ALIGNMENT
2336 VMOVDQA VMOVDQA_MEMdq_XMMdq DATAXFER AVX AVX ATTRIBUTES: AVX_REQUIRES_ALIGNMENT REQUIRES_ALIGNMENT
2337 VMOVDQA VMOVDQA_XMMdq_XMMdq_7F DATAXFER AVX AVX ATTRIBUTES: AVX_REQUIRES_ALIGNMENT REQUIRES_ALIGNMENT
2338 VMOVDQA VMOVDQA_YMMqq_MEMqq DATAXFER AVX AVX ATTRIBUTES: AVX_REQUIRES_ALIGNMENT REQUIRES_ALIGNMENT
2339 VMOVDQA VMOVDQA_YMMqq_YMMqq_6F DATAXFER AVX AVX ATTRIBUTES: AVX_REQUIRES_ALIGNMENT REQUIRES_ALIGNMENT
2340 VMOVDQA VMOVDQA_MEMqq_YMMqq DATAXFER AVX AVX ATTRIBUTES: AVX_REQUIRES_ALIGNMENT REQUIRES_ALIGNMENT
2341 VMOVDQA VMOVDQA_YMMqq_YMMqq_7F DATAXFER AVX AVX ATTRIBUTES: AVX_REQUIRES_ALIGNMENT REQUIRES_ALIGNMENT

2350 VMOVDQU VMOVDQU_XMMdq_MEMdq DATAXFER AVX AVX ATTRIBUTES:
2351 VMOVDQU VMOVDQU_XMMdq_XMMdq_6F DATAXFER AVX AVX ATTRIBUTES:
2352 VMOVDQU VMOVDQU_YMMqq_MEMqq DATAXFER AVX AVX ATTRIBUTES:
2353 VMOVDQU VMOVDQU_YMMqq_YMMqq_6F DATAXFER AVX AVX ATTRIBUTES:
2354 VMOVDQU VMOVDQU_MEMdq_XMMdq DATAXFER AVX AVX ATTRIBUTES:
2355 VMOVDQU VMOVDQU_XMMdq_XMMdq_7F DATAXFER AVX AVX ATTRIBUTES:
2356 VMOVDQU VMOVDQU_MEMqq_YMMqq DATAXFER AVX AVX ATTRIBUTES:
2357 VMOVDQU VMOVDQU_YMMqq_YMMqq_7F DATAXFER AVX AVX ATTRIBUTES:

2471 VMOVLPD VMOVLPD_XMMdq_XMMdq_MEMq DATAXFER AVX AVX ATTRIBUTES:
2472 VMOVLPD VMOVLPD_MEMq_XMMq DATAXFER AVX AVX ATTRIBUTES:

2480 VMOVLPS VMOVLPS_XMMdq_XMMdq_MEMq DATAXFER AVX AVX ATTRIBUTES:
2481 VMOVLPS VMOVLPS_MEMq_XMMq DATAXFER AVX AVX ATTRIBUTES:
2648 VMOVUPS VMOVUPS_XMMdq_MEMdq DATAXFER AVX AVX ATTRIBUTES:
2649 VMOVUPS VMOVUPS_XMMdq_XMMdq_10 DATAXFER AVX AVX ATTRIBUTES:
2650 VMOVUPS VMOVUPS_MEMdq_XMMdq DATAXFER AVX AVX ATTRIBUTES:
2651 VMOVUPS VMOVUPS_XMMdq_XMMdq_11 DATAXFER AVX AVX ATTRIBUTES:
2652 VMOVUPS VMOVUPS_YMMqq_MEMqq DATAXFER AVX AVX ATTRIBUTES:
2653 VMOVUPS VMOVUPS_YMMqq_YMMqq_10 DATAXFER AVX AVX ATTRIBUTES:
2654 VMOVUPS VMOVUPS_MEMqq_YMMqq DATAXFER AVX AVX ATTRIBUTES:
2655 VMOVUPS VMOVUPS_YMMqq_YMMqq_11 DATAXFER AVX AVX ATTRIBUTES:

2666 VMOVUPD VMOVUPD_XMMdq_MEMdq DATAXFER AVX AVX ATTRIBUTES:
2667 VMOVUPD VMOVUPD_XMMdq_XMMdq_10 DATAXFER AVX AVX ATTRIBUTES:
2668 VMOVUPD VMOVUPD_MEMdq_XMMdq DATAXFER AVX AVX ATTRIBUTES:
2669 VMOVUPD VMOVUPD_XMMdq_XMMdq_11 DATAXFER AVX AVX ATTRIBUTES:
2670 VMOVUPD VMOVUPD_YMMqq_MEMqq DATAXFER AVX AVX ATTRIBUTES:
2671 VMOVUPD VMOVUPD_YMMqq_YMMqq_10 DATAXFER AVX AVX ATTRIBUTES:
2672 VMOVUPD VMOVUPD_MEMqq_YMMqq DATAXFER AVX AVX ATTRIBUTES:
2673 VMOVUPD VMOVUPD_YMMqq_YMMqq_11 DATAXFER AVX AVX ATTRIBUTES:
2796 VMOVHPD VMOVHPD_XMMdq_XMMq_MEMq DATAXFER AVX AVX ATTRIBUTES:
2797 VMOVHPD VMOVHPD_MEMq_XMMdq DATAXFER AVX AVX ATTRIBUTES:

2814 VMOVHPS VMOVHPS_XMMdq_XMMq_MEMq DATAXFER AVX AVX ATTRIBUTES:
2815 VMOVHPS VMOVHPS_MEMq_XMMdq DATAXFER AVX AVX ATTRIBUTES:

2995 VMOVAPD VMOVAPD_XMMdq_MEMdq DATAXFER AVX AVX ATTRIBUTES: AVX_REQUIRES_ALIGNMENT REQUIRES_ALIGNMENT
2996 VMOVAPD VMOVAPD_XMMdq_XMMdq_28 DATAXFER AVX AVX ATTRIBUTES: AVX_REQUIRES_ALIGNMENT REQUIRES_ALIGNMENT
2997 VMOVAPD VMOVAPD_MEMdq_XMMdq DATAXFER AVX AVX ATTRIBUTES: AVX_REQUIRES_ALIGNMENT REQUIRES_ALIGNMENT
2998 VMOVAPD VMOVAPD_XMMdq_XMMdq_29 DATAXFER AVX AVX ATTRIBUTES: AVX_REQUIRES_ALIGNMENT REQUIRES_ALIGNMENT
2999 VMOVAPD VMOVAPD_YMMqq_MEMqq DATAXFER AVX AVX ATTRIBUTES: AVX_REQUIRES_ALIGNMENT REQUIRES_ALIGNMENT
3000 VMOVAPD VMOVAPD_YMMqq_YMMqq_28 DATAXFER AVX AVX ATTRIBUTES: AVX_REQUIRES_ALIGNMENT REQUIRES_ALIGNMENT
3001 VMOVAPD VMOVAPD_MEMqq_YMMqq DATAXFER AVX AVX ATTRIBUTES: AVX_REQUIRES_ALIGNMENT REQUIRES_ALIGNMENT
3002 VMOVAPD VMOVAPD_YMMqq_YMMqq_29 DATAXFER AVX AVX ATTRIBUTES: AVX_REQUIRES_ALIGNMENT REQUIRES_ALIGNMENT

3025 VMOVAPS VMOVAPS_XMMdq_MEMdq DATAXFER AVX AVX ATTRIBUTES: AVX_REQUIRES_ALIGNMENT REQUIRES_ALIGNMENT
3026 VMOVAPS VMOVAPS_XMMdq_XMMdq_28 DATAXFER AVX AVX ATTRIBUTES: AVX_REQUIRES_ALIGNMENT REQUIRES_ALIGNMENT
3027 VMOVAPS VMOVAPS_MEMdq_XMMdq DATAXFER AVX AVX ATTRIBUTES: AVX_REQUIRES_ALIGNMENT REQUIRES_ALIGNMENT
3028 VMOVAPS VMOVAPS_XMMdq_XMMdq_29 DATAXFER AVX AVX ATTRIBUTES: AVX_REQUIRES_ALIGNMENT REQUIRES_ALIGNMENT
3029 VMOVAPS VMOVAPS_YMMqq_MEMqq DATAXFER AVX AVX ATTRIBUTES: AVX_REQUIRES_ALIGNMENT REQUIRES_ALIGNMENT
3030 VMOVAPS VMOVAPS_YMMqq_YMMqq_28 DATAXFER AVX AVX ATTRIBUTES: AVX_REQUIRES_ALIGNMENT REQUIRES_ALIGNMENT
3031 VMOVAPS VMOVAPS_MEMqq_YMMqq DATAXFER AVX AVX ATTRIBUTES: AVX_REQUIRES_ALIGNMENT REQUIRES_ALIGNMENT
3032 VMOVAPS VMOVAPS_YMMqq_YMMqq_29 DATAXFER AVX AVX ATTRIBUTES: AVX_REQUIRES_ALIGNMENT REQUIRES_ALIGNMENT
 */
