/* Copyright 2016 Peter Goodman (peter@trailofbits.com), all rights reserved. */

#ifndef MCSEMA_ARCH_X86_SEMANTICS_XOP_H_
#define MCSEMA_ARCH_X86_SEMANTICS_XOP_H_

/*
 * See https://en.wikipedia.org/wiki/XOP_instruction_set

1990 VPCMOV VPCMOV_XMMdq_XMMdq_MEMdq_XMMdq XOP XOP XOP ATTRIBUTES:
1991 VPCMOV VPCMOV_XMMdq_XMMdq_XMMdq_XMMdq XOP XOP XOP ATTRIBUTES:
1992 VPCMOV VPCMOV_XMMdq_XMMdq_XMMdq_MEMdq XOP XOP XOP ATTRIBUTES:
1993 VPCMOV VPCMOV_XMMdq_XMMdq_XMMdq_XMMdq XOP XOP XOP ATTRIBUTES:
1994 VPCMOV VPCMOV_YMMqq_YMMqq_MEMqq_YMMqq XOP XOP XOP ATTRIBUTES:
1995 VPCMOV VPCMOV_YMMqq_YMMqq_YMMqq_YMMqq XOP XOP XOP ATTRIBUTES:
1996 VPCMOV VPCMOV_YMMqq_YMMqq_YMMqq_MEMqq XOP XOP XOP ATTRIBUTES:
1997 VPCMOV VPCMOV_YMMqq_YMMqq_YMMqq_YMMqq XOP XOP XOP ATTRIBUTES:
 */

#endif  // MCSEMA_ARCH_X86_SEMANTICS_XOP_H_
